import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home(list) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cinema Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Filmes em Destaque - final
        </h1>

        <Link href="/busca">Buscar Filmes</Link>
          <ul>
           {list.list.map((item) => 
              <li key={item.id}>
                <Link href={`/movie/${item.id}`}>  
                <>
                  <Image alt ="post filme" src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width="150"/><br/>
                  {item.title}
                </>
                </Link> 
             </li>
            )}
          </ul>
           

      </main>
      <footer className={styles.footer}>
        <Link href="/sobre">Sobre mim</Link>

        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(){
  const res = await fetch('http://localhost:3000/api/trending')
  const json = await res.json()
  return{
    props: {
      list: json.list
    }     
  }
}
